#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/10/27 6:08 PM
# @Author  : Dora
# @File    : practiceday8.py


#题目：输出9*9乘法口诀表

for i in range(1,10):
    for j in range(1,10):
        x = i * j
        print('%d * %d = %d'%(i, j, x))

